apiVersion: apps/v1
kind: Deployment
metadata:
  name: ikli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ikli
  template:
    metadata:
      labels:
        app: ikli
    spec:
      containers:
      - image: okteto.dev/ikli:latest
        name: ikli
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "lenskart.com"
        - name: Vless_UUID
          value: "5a441365-9d24-497e-80c0-39ab9fcefb3a"
        - name: Vless_Path
          value: "/reryu6"
        - name: Vmess_UUID
          value: "5a441365-9d24-497e-80c0-39ab9fcefb3a"
        - name: Vmess_Path
          value: "/nmj896"
        - name: Share_Path
          value: "/share233"
